export const FETCH_EMPLOYEES_LOADING = 'FETCH_EMPLOYEES_LOADING';
export const FETCH_EMPLOYEES_LOADED = 'FETCH_EMPLOYEES_LOADED';
export const FETCH_EMPLOYEES_ERROR = 'FETCH_EMPLOYEES_ERROR';

export const FETCH_EMPLOYEE_GROUPS_LOADING = 'FETCH_EMPLOYEES_GROUPS_LOADING';
export const FETCH_EMPLOYEE_GROUPS_LOADED = 'FETCH_EMPLOYEES_GROUPS_LOADED';
export const FETCH_EMPLOYEE_GROUPS_ERROR = 'FETCH_EMPLOYEES_GROUPS_ERROR';

export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_ERROR = 'CREATE_GROUP_ERROR';
