export const SIGNUP_STEP_ONE = 'SIGNUP_STEP_ONE';
export const SIGNUP_STEP_TWO_LOADING = 'SIGNUP_STEP_TWO_LOADING';
export const SIGNUP_STEP_TWO_LOADED = 'SIGNUP_STEP_TWO_LOADED';
export const SIGNUP_STEP_TWO_ERROR = 'SIGNUP_STEP_TWO_ERROR';

export const LOGOUT = 'LOGOUT';
